/* eslint-disable */
// AUTOGENERATED — do not edit by hand.
// Source: docs/web/*.schema.json
// Regenerate with: npm run codegen

/**
 * Companion to `trace.schema.json` describing the activation summary captured by an `ActivationProbe` for a single generation. Carries per-step `activations: ActivationLayerEntry[]` plus a top-level `activation_metadata` block, and a cross-tokenizer alignment field (`decoded_text_offset`) on every step so two traces produced by different tokenizers can still be aligned position-for-position. Consumed by `compare_activations` and the Activations tab UI. One file == one prompt == one generation.
 */
export interface ActivationTrace {
  /**
   * Semver of this schema. Bumped independently of the main trace schema. Consumers must hard-fail on unknown major. 1.1.0 adds the optional per-step `activation_sidecar_ref` field as a backwards-compatible additive change for the Tier 2 sidecar.
   */
  schema_version: string;
  activation_metadata: ActivationMetadata;
  /**
   * Per-generation-step activation records. `steps[i].step` MUST equal `i`. Iteration ends early on EOS, so length matches the parent trace's `steps` length.
   */
  steps: ActivationStep[];
}
/**
 * Per-trace metadata describing the ActivationProbe captures. Required whenever any step carries an `activations` array.
 *
 * This interface was referenced by `ActivationTrace`'s JSON-Schema
 * via the `definition` "ActivationMetadata".
 */
export interface ActivationMetadata {
  /**
   * Submodule names captured by the probe, in the order their per-(layer, submodule) entries appear inside each step's `activations` array (e.g. `["resid_pre", "resid_post", "mlp.down_proj", "o_proj"]`).
   *
   * @minItems 1
   */
  captured_submodules: [string, ...string[]];
  /**
   * Total number of decoder layers in the model (regardless of how many were captured).
   */
  num_layers: number;
  /**
   * Per-layer residual-stream / hidden dimension. Used by consumers to interpret `top_neurons.index` ranges.
   */
  hidden_dim: number;
  /**
   * Stable identifier for the tokenizer that produced this trace's token ids. Two traces with matching fingerprints can be aligned by `token_id`; mismatching fingerprints must fall back to position alignment via `decoded_text_offset`.
   */
  tokenizer_fingerprint: string;
  /**
   * Zero-indexed decoder layer indices that the probe captured (ascending; duplicate-free). When omitted, consumers MAY assume all layers `[0, num_layers)` are captured.
   */
  captured_layers?: number[];
}
/**
 * Activation record for a single generation step. The `token_id` and `decoded_text_offset` fields carry the cross-tokenizer alignment information so this entry can be matched against the corresponding entry in another trace.
 *
 * This interface was referenced by `ActivationTrace`'s JSON-Schema
 * via the `definition` "ActivationStep".
 */
export interface ActivationStep {
  /**
   * Zero-indexed position in the generation loop. MUST equal the array index.
   */
  step: number;
  /**
   * Selected token id at this step. Used for `token_id` alignment when the two compared traces share a tokenizer (matching `tokenizer_fingerprint`).
   */
  token_id: number;
  /**
   * Character offset of this step's decoded token in the concatenated decoded text. Used for `position` alignment when the two compared traces use different tokenizers — alignment falls back to matching equal-or-overlapping character offsets in the rendered text.
   */
  decoded_text_offset: number;
  /**
   * Per (layer, submodule) activation summary entries for this step. Ordering is layer-major then submodule-major following `activation_metadata.captured_submodules`.
   */
  activations: ActivationLayerEntry[];
  /**
   * Relative path (or URL) of the Tier 2 `.npz` activation sidecar for this step, or `null` when no sidecar was written (the default; sidecars are opt-in via `--capture-full-activations`). The referenced file conforms to `activation-sidecar.schema.json`.
   */
  activation_sidecar_ref?: string | null;
}
/**
 * Summary statistics for one (step, layer, submodule) activation tensor. Captured inline (Tier 1); the full tensor lives in an optional sidecar.
 *
 * This interface was referenced by `ActivationTrace`'s JSON-Schema
 * via the `definition` "ActivationLayerEntry".
 */
export interface ActivationLayerEntry {
  /**
   * Zero-indexed decoder layer index; when `activation_metadata.captured_layers` is present, MUST appear in it.
   */
  layer: number;
  /**
   * Submodule name (e.g. `resid_pre`, `mlp.down_proj`, `o_proj`). MUST appear in `activation_metadata.captured_submodules`.
   */
  submodule: string;
  /**
   * L2 norm of the captured activation vector at this (step, layer, submodule).
   */
  l2_norm: number;
  /**
   * Mean absolute value across the `hidden_dim` neurons of the captured activation vector.
   */
  mean_abs: number;
  /**
   * Fraction of neurons whose absolute value lies below the probe's near-zero threshold.
   */
  sparsity: number;
  /**
   * Highest-magnitude neurons within this (step, layer, submodule), sorted by descending `|value|`.
   */
  top_neurons: TopNeuron[];
}
/**
 * This interface was referenced by `ActivationTrace`'s JSON-Schema
 * via the `definition` "TopNeuron".
 */
export interface TopNeuron {
  /**
   * Zero-indexed neuron position within the layer's hidden dimension. MUST be `< activation_metadata.hidden_dim`.
   */
  index: number;
  /**
   * Signed activation value at this neuron index (not absolute).
   */
  value: number;
}
/**
 * On-disk payload produced by `compare_activations(trace_a, trace_b, ...)`. Carries per-step `delta` records, one per (step, layer, submodule), plus alignment metadata describing how the two source traces were matched up (`token_id` vs `position`). Consumed by the CLI `diff` subcommand and the diff-mode UI. One file == one (trace_a, trace_b) pair.
 */
export interface ActivationDiff {
  /**
   * Semver of this schema. Bumped independently of the main trace and activation schemas. Consumers must hard-fail on unknown major.
   */
  schema_version: string;
  alignment: Alignment;
  /**
   * Per-step diff records, ordered by the aligned `step` index. Length equals the number of successfully aligned steps; unmatched steps from either side are listed in `alignment.mismatches` instead.
   */
  steps: DiffStep[];
}
/**
 * Records the alignment mode applied by `compare_activations`, the tokenizer fingerprints of the two source traces, and any positions the comparator could not align.
 *
 * This interface was referenced by `ActivationDiff`'s JSON-Schema
 * via the `definition` "Alignment".
 */
export interface Alignment {
  /**
   * Alignment strategy used. `token_id` zips traces on step index, requiring identical token ids; `position` zips on `decoded_text_offset`, tolerating different tokenizers; `auto` picks `token_id` when the fingerprints match, else `position`.
   */
  mode: 'token_id' | 'position' | 'auto';
  /**
   * `activation_metadata.tokenizer_fingerprint` of trace A. Equal to `tokenizer_b_fingerprint` whenever `mode == "token_id"` (or when `mode == "auto"` resolved to id-based alignment).
   */
  tokenizer_a_fingerprint: string;
  /**
   * `activation_metadata.tokenizer_fingerprint` of trace B.
   */
  tokenizer_b_fingerprint: string;
  /**
   * Steps that could not be aligned (e.g. divergent token ids under `token_id` mode, or non-overlapping decoded-text offsets under `position` mode). Empty array when the two traces aligned cleanly.
   */
  mismatches: AlignmentMismatch[];
}
/**
 * A single step where alignment failed. At least one of `step_a` or `step_b` is present, allowing the consumer to render the unmatched step on the correct side of the diff UI.
 *
 * This interface was referenced by `ActivationDiff`'s JSON-Schema
 * via the `definition` "AlignmentMismatch".
 */
export interface AlignmentMismatch {
  /**
   * Zero-indexed step in trace A that could not be aligned, or null if the unmatched step is on the B side.
   */
  step_a?: number | null;
  /**
   * Zero-indexed step in trace B that could not be aligned, or null if the unmatched step is on the A side.
   */
  step_b?: number | null;
  /**
   * Human-readable explanation (e.g. `"token_id_divergence"`, `"offset_gap"`, `"trailing_steps_in_a"`).
   */
  reason: string;
}
/**
 * Diff record for a single aligned step. Carries the cross-tokenizer alignment fields from both source traces so consumers can re-render the corresponding token on either side without revisiting the originals.
 *
 * This interface was referenced by `ActivationDiff`'s JSON-Schema
 * via the `definition` "DiffStep".
 */
export interface DiffStep {
  /**
   * Zero-indexed step in the aligned output.
   */
  step: number;
  /**
   * Selected `token_id` from trace A at this step.
   */
  token_id_a: number;
  /**
   * Selected `token_id` from trace B at this step. Equal to `token_id_a` under `token_id` alignment; may differ under `position` alignment.
   */
  token_id_b: number;
  /**
   * Character offset of this step's decoded token in trace A's decoded text.
   */
  decoded_text_offset_a: number;
  /**
   * Character offset of this step's decoded token in trace B's decoded text.
   */
  decoded_text_offset_b: number;
  /**
   * Per (layer, submodule) deltas. Ordering matches the producer's iteration over the captured submodules of trace A.
   */
  delta: LayerDelta[];
}
/**
 * Difference between trace A and trace B for one (layer, submodule) at one aligned step.
 *
 * This interface was referenced by `ActivationDiff`'s JSON-Schema
 * via the `definition` "LayerDelta".
 */
export interface LayerDelta {
  /**
   * Zero-indexed decoder layer index.
   */
  layer: number;
  /**
   * Submodule name (e.g. `resid_pre`, `mlp.down_proj`). MUST appear in both source traces' `activation_metadata.captured_submodules`.
   */
  submodule: string;
  /**
   * L2 norm of the activation difference vector `(a - b)` at this (layer, submodule).
   */
  l2: number;
  /**
   * Cosine similarity between trace A's and trace B's activation vectors. `1.0` means identical direction; `-1.0` means opposite.
   */
  cosine: number;
  /**
   * Neurons with the largest absolute delta at this (layer, submodule), sorted by descending `|delta|`.
   */
  top_changed_neurons: TopChangedNeuron[];
}
/**
 * This interface was referenced by `ActivationDiff`'s JSON-Schema
 * via the `definition` "TopChangedNeuron".
 */
export interface TopChangedNeuron {
  /**
   * Zero-indexed neuron position within the layer's hidden dimension.
   */
  index: number;
  /**
   * Signed delta `(a_value - b_value)` at this neuron index.
   */
  delta: number;
}
import type { Step, Trace } from './trace';

/**
 * A Step from the canonical trace schema extended with the optional
 * activation fields a producer adds when an ActivationProbe is attached.
 * `activations` and `decoded_text_offset` are absent on traces produced
 * without an ActivationProbe; consumers MUST treat them as optional.
 */
export interface StepWithActivations extends Step {
  decoded_text_offset?: number;
  activations?: ActivationLayerEntry[];
}

/**
 * A canonical Trace extended with the optional activation fields. Producers
 * that emit activations inline (rather than as a separate
 * activation_trace.json file) MUST conform to this extended shape.
 */
export interface TraceWithActivations extends Omit<Trace, 'steps'> {
  activation_metadata?: ActivationMetadata;
  steps: StepWithActivations[];
}
