/* eslint-disable */
// AUTOGENERATED — do not edit by hand.
// Source: docs/web/*.schema.json
// Regenerate with: npm run codegen

/**
 * Canonical JSON payload for a single adaptive-probe generation trace. Produced by `llm_token_heatmap.generate_with_adaptive_probe` after lightweight serialization, and consumed by the CLI exporter, FastAPI backend, and web frontend. One file == one prompt == one generation.
 */
export interface Trace {
  /**
   * Semver of this schema. Bump major on breaking changes; consumers must hard-fail on unknown major.
   */
  schema_version: string;
  attention_metadata?: AttentionMetadata;
  /**
   * Per-trace metadata: model identity, sampling parameters, and prompt.
   */
  metadata: {
    /**
     * HuggingFace model id or local path used for generation.
     */
    model: string;
    /**
     * The user prompt before any chat-template wrapping.
     */
    prompt: string;
    /**
     * Optional system message used when use_chat_template=true.
     */
    system_prompt?: string | null;
    /**
     * Whether tokenizer.apply_chat_template was applied to the prompt.
     */
    use_chat_template?: boolean;
    /**
     * Full decoded text including the prompt, with special tokens skipped.
     */
    generated_text: string;
    /**
     * RFC 3339 timestamp at which the trace finished generating.
     */
    generated_at: string;
    /**
     * Device that ran inference.
     */
    device?: 'cpu' | 'cuda' | 'mps';
    /**
     * PyTorch dtype used for the forward pass.
     */
    dtype?: string;
    /**
     * Tokenizer vocabulary size; used by the UI to compute rank as a percentile if requested.
     */
    vocab_size?: number;
    generation_params: {
      max_new_tokens: number;
      temperature: number;
      top_p: number;
      /**
       * 0 disables top-k filtering during sampling.
       */
      sample_top_k: number;
    };
    probe_config: {
      min_k: number;
      max_k: number;
      mass_threshold: number;
      /**
       * Numerical stability constant used inside the probe.
       */
      eps?: number;
    };
  };
  /**
   * Prompt tokens, surfaced separately so the UI can render the prompt with the same hover affordances as generated tokens. These are the tokens fed into the model before step 0 (after chat-template wrapping, if any).
   */
  tokens: {
    prompt_token_ids: number[];
    /**
     * Decoded prompt tokens; same length as prompt_token_ids.
     */
    prompt_tokens: string[];
  };
  /**
   * Per-generation-step records. `steps[i].step` MUST equal `i`. Iteration ends early on EOS, so length <= generation_params.max_new_tokens.
   */
  steps: Step[];
}
/**
 * Per-trace metadata describing the AttentionProbe captures. Present whenever any step carries an `attention` array.
 *
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "AttentionMetadata".
 */
export interface AttentionMetadata {
  /**
   * Total number of decoder layers in the model (regardless of how many were captured).
   */
  num_layers: number;
  /**
   * Number of query attention heads per layer.
   */
  num_attention_heads: number;
  /**
   * Number of key/value heads per layer (equals num_attention_heads for MHA; smaller under Grouped Query Attention).
   */
  num_key_value_heads: number;
  /**
   * Per-head hidden dimension.
   */
  head_dim: number;
  /**
   * Zero-indexed decoder layer indices that the probe captured (ascending; duplicate-free).
   */
  captured_layers: number[];
}
/**
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "Step".
 */
export interface Step {
  /**
   * Zero-indexed position in the generation loop.
   */
  step: number;
  selected: SelectedToken;
  raw: Distribution;
  processed: Distribution;
  /**
   * Optional per-layer logit-lens projections for this step. Present when a LogitLens probe was attached during generation. Ordered by layer_idx ascending.
   */
  logit_lens?: LogitLensLayer[];
  /**
   * Tier 1 inline attention summary, one entry per captured decoder layer. Absent for traces produced without an AttentionProbe.
   */
  attention?: AttentionLayerEntry[];
  /**
   * URI pointer to a Tier 2 sidecar payload (full attention distribution and/or raw Q/K/V tensors) for this step, or null when no sidecar was written. Sidecar files follow `docs/web/attention-sidecar.schema.json`.
   */
  attention_sidecar_ref?: string | null;
}
/**
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "SelectedToken".
 */
export interface SelectedToken {
  token_id: number;
  /**
   * Decoded text of the selected token (special tokens NOT skipped).
   */
  token: string;
}
/**
 * Outcome of one AdaptiveTokenProbe forward pass for one (step, source) pair.
 *
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "Distribution".
 */
export interface Distribution {
  /**
   * Number of candidates kept by the adaptive rule (clamped to [min_k, max_k]).
   */
  k_used: number;
  /**
   * Shannon entropy of the full next-token distribution, in nats.
   */
  entropy: number;
  /**
   * Cumulative probability mass covered by the kept candidates.
   */
  top_mass_used: number;
  selected_prob: number;
  /**
   * log(selected_prob + eps); may be -inf-ish but always finite under the probe's eps clamp.
   */
  selected_logprob: number;
  /**
   * 1-indexed rank of the selected token across the FULL vocabulary.
   */
  selected_rank: number;
  /**
   * Kept candidates, length == k_used, sorted by descending prob.
   */
  candidates: Candidate[];
}
/**
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "Candidate".
 */
export interface Candidate {
  /**
   * 1-indexed position within the kept candidates.
   */
  rank: number;
  token_id: number;
  token: string;
  prob: number;
  logprob: number;
}
/**
 * Logit-lens projection of one decoder layer's residual stream for one generation step.
 *
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "LogitLensLayer".
 */
export interface LogitLensLayer {
  /**
   * Zero-indexed decoder layer position.
   */
  layer_idx: number;
  /**
   * Highest-probability candidates after projecting this layer's hidden state through (optionally) the final LayerNorm and the lm_head.
   */
  top_k: LogitLensCandidate[];
  /**
   * Shannon entropy (nats) of this layer's full next-token distribution.
   */
  entropy: number;
  /**
   * 1-indexed rank of the step's selected token within this layer's distribution.
   */
  selected_token_rank: number;
  /**
   * Probability assigned to the step's selected token by this layer's distribution.
   */
  selected_token_prob: number;
}
/**
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "LogitLensCandidate".
 */
export interface LogitLensCandidate {
  /**
   * 1-indexed rank within the top_k candidates.
   */
  rank: number;
  token_id: number;
  token: string;
  prob: number;
  logprob: number;
}
/**
 * Tier 1 attention summary for a single (step, layer). Head-level aggregation lives in a downstream ticket; the per-layer scalars here are the mean across heads.
 *
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "AttentionLayerEntry".
 */
export interface AttentionLayerEntry {
  /**
   * Zero-indexed decoder layer index; must appear in attention_metadata.captured_layers.
   */
  layer: number;
  /**
   * Mean Shannon entropy (nats) of the per-head attention distribution over previous positions, averaged across heads.
   */
  entropy: number;
  /**
   * Mean attention weight on the current (last) position, averaged across heads.
   */
  self_weight: number;
  /**
   * Mean attention weight on position 0 (typically the BOS / sink token), averaged across heads.
   */
  bos_weight: number;
  /**
   * Most-attended source positions for this layer, aggregated across heads, sorted by descending weight.
   */
  top_positions: AttentionTopPosition[];
  /**
   * Mean L2 norm of the current-token Q vector across heads.
   */
  q_norm: number;
  /**
   * Mean L2 norm of the current-token K vector across heads.
   */
  k_norm: number;
  /**
   * Mean L2 norm of the current-token V vector across heads.
   */
  v_norm: number;
  /**
   * Mean angle in degrees between the head's Q vector and the K vector of its top-attended source position, averaged across heads.
   */
  qk_alignment_angle: number;
}
/**
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "AttentionTopPosition".
 */
export interface AttentionTopPosition {
  /**
   * Zero-indexed source position in the key sequence.
   */
  position: number;
  /**
   * Aggregate attention weight on this position (mean across heads).
   */
  weight: number;
}
