/* eslint-disable */
// AUTOGENERATED — do not edit by hand.
// Source: docs/web/*.schema.json
// Regenerate with: npm run codegen

/**
 * Canonical JSON payload for a single adaptive-probe generation trace. Produced by `llm_token_heatmap.generate_with_adaptive_probe` after lightweight serialization, and consumed by the CLI exporter, FastAPI backend, and web frontend. One file == one prompt == one generation.
 */
export interface Trace {
  /**
   * Semver of this schema. Bump major on breaking changes; consumers must hard-fail on unknown major.
   */
  schema_version: string;
  attention_metadata?: AttentionMetadata;
  activation_metadata?: ActivationMetadata;
  manifold?: Manifold;
  /**
   * Per-trace metadata: model identity, sampling parameters, and prompt.
   */
  metadata: {
    /**
     * HuggingFace model id or local path used for generation.
     */
    model: string;
    /**
     * The user prompt before any chat-template wrapping.
     */
    prompt: string;
    /**
     * Optional system message used when use_chat_template=true.
     */
    system_prompt?: string | null;
    /**
     * Whether tokenizer.apply_chat_template was applied to the prompt.
     */
    use_chat_template?: boolean;
    /**
     * Full decoded text including the prompt, with special tokens skipped.
     */
    generated_text: string;
    /**
     * RFC 3339 timestamp at which the trace finished generating.
     */
    generated_at: string;
    /**
     * Device that ran inference.
     */
    device?: 'cpu' | 'cuda' | 'mps';
    /**
     * PyTorch dtype used for the forward pass.
     */
    dtype?: string;
    /**
     * Tokenizer vocabulary size; used by the UI to compute rank as a percentile if requested.
     */
    vocab_size?: number;
    generation_params: {
      max_new_tokens: number;
      temperature: number;
      top_p: number;
      /**
       * 0 disables top-k filtering during sampling.
       */
      sample_top_k: number;
    };
    probe_config: {
      min_k: number;
      max_k: number;
      mass_threshold: number;
      /**
       * Numerical stability constant used inside the probe.
       */
      eps?: number;
    };
  };
  /**
   * Prompt tokens, surfaced separately so the UI can render the prompt with the same hover affordances as generated tokens. These are the tokens fed into the model before step 0 (after chat-template wrapping, if any).
   */
  tokens: {
    prompt_token_ids: number[];
    /**
     * Decoded prompt tokens; same length as prompt_token_ids.
     */
    prompt_tokens: string[];
  };
  /**
   * Per-generation-step records. `steps[i].step` MUST equal `i`. Iteration ends early on EOS, so length <= generation_params.max_new_tokens.
   */
  steps: Step[];
}
/**
 * Per-trace metadata describing the AttentionProbe captures. Present whenever any step carries an `attention` array.
 *
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "AttentionMetadata".
 */
export interface AttentionMetadata {
  /**
   * Total number of decoder layers in the model (regardless of how many were captured).
   */
  num_layers: number;
  /**
   * Number of query attention heads per layer.
   */
  num_attention_heads: number;
  /**
   * Number of key/value heads per layer (equals num_attention_heads for MHA; smaller under Grouped Query Attention).
   */
  num_key_value_heads: number;
  /**
   * Per-head hidden dimension.
   */
  head_dim: number;
  /**
   * Zero-indexed decoder layer indices that the probe captured (ascending; duplicate-free).
   */
  captured_layers: number[];
}
/**
 * Per-trace metadata describing the ActivationProbe captures. Mirrors `activation.schema.json#/$defs/ActivationMetadata`.
 *
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "ActivationMetadata".
 */
export interface ActivationMetadata {
  /**
   * Submodule names captured by the probe, in the order their per-(layer, submodule) entries appear inside each step's `activations` array.
   *
   * @minItems 1
   */
  captured_submodules: [string, ...string[]];
  /**
   * Total number of decoder layers in the model.
   */
  num_layers: number;
  /**
   * Per-layer residual-stream / hidden dimension.
   */
  hidden_dim: number;
  /**
   * Stable identifier for the tokenizer that produced this trace's token ids.
   */
  tokenizer_fingerprint: string;
  /**
   * Zero-indexed decoder layer indices that the probe captured (ascending; duplicate-free).
   */
  captured_layers?: number[];
}
/**
 * Manifold analysis results, one entry per analyzed (layer, submodule) activation cloud. See `llm_token_heatmap/manifold.py`.
 *
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "Manifold".
 */
export interface Manifold {
  /**
   * Semver of the manifold payload shape.
   */
  schema_version: string;
  /**
   * Dimensionality-reduction method used for the projection.
   */
  method: 'pca';
  /**
   * Number of projection components requested.
   */
  n_components: number;
  /**
   * One manifold-analysis entry per analyzed (layer, submodule) cloud.
   */
  layers: ManifoldLayer[];
  scalar?: ManifoldScalar;
}
/**
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "ManifoldLayer".
 */
export interface ManifoldLayer {
  layer: number;
  submodule: string;
  /**
   * Number of token positions (rows) in the analyzed cloud.
   */
  n_positions: number;
  /**
   * Activation vector dimension.
   */
  hidden_dim: number;
  /**
   * Generation-step index for each row, aligned with `projection.coords`.
   */
  positions: number[];
  pca: ManifoldPca;
  /**
   * Effective dimensionality (Σλ)²/Σλ²; null when undefined.
   */
  participation_ratio: number | null;
  intrinsic_dimension: ManifoldIntrinsicDimension;
  projection: ManifoldProjection;
  trajectory_curvature: ManifoldCurvature;
  periodicity: ManifoldPeriodicity;
  probe?: ManifoldProbe;
}
/**
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "ManifoldPca".
 */
export interface ManifoldPca {
  /**
   * Covariance eigenvalues, descending (capped).
   */
  eigenvalues: number[];
  explained_variance_ratio: number[];
  cumulative_variance_ratio: number[];
}
/**
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "ManifoldIntrinsicDimension".
 */
export interface ManifoldIntrinsicDimension {
  /**
   * TwoNN intrinsic-dimension estimate; null when not estimable.
   */
  twonn: number | null;
}
/**
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "ManifoldProjection".
 */
export interface ManifoldProjection {
  n_components: number;
  /**
   * Per-position PCA scores; row i is the projection of position i. Shape (n_positions, n_components).
   */
  coords: number[][];
}
/**
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "ManifoldCurvature".
 */
export interface ManifoldCurvature {
  /**
   * Mean interior discrete curvature; null when undefined.
   */
  mean: number | null;
  /**
   * Per-position curvature; endpoints and degenerate points are null.
   */
  per_position: (number | null)[];
}
/**
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "ManifoldPeriodicity".
 */
export interface ManifoldPeriodicity {
  /**
   * Period (in positions) of the dominant non-DC FFT component of PC1; null when none.
   */
  dominant_period: number | null;
  /**
   * Normalized spectral power of the dominant component (peak / total).
   */
  power: number;
  peak_frequency: number | null;
}
/**
 * Supervised linear-probe result for this cloud: how well the manifold's task scalar is linearly decodable from the activations. See `llm_token_heatmap/probe.py`.
 *
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "ManifoldProbe".
 */
export interface ManifoldProbe {
  /**
   * Name of the probed scalar (matches `manifold.scalar.name`).
   */
  scalar: string;
  /**
   * Cross-validated R² of the scalar decode; null when too few positions to cross-validate.
   */
  r2_cv: number | null;
  /**
   * In-sample R² of the full-data fit; null when the probe could not be fit.
   */
  r2_full: number | null;
  /**
   * PCA rank the cloud was reduced to before regressing.
   */
  n_components: number;
  /**
   * Number of CV folds used (0 when CV was skipped).
   */
  cv_folds: number;
  circular?: ManifoldProbeCircular;
}
/**
 * Helix test: how decodable the *circular* coordinate cos/sin(2π·scalar/period) of the scalar is, at the best-fitting period. High circular r2_cv together with a high linear probe r2_cv is the helix signature (a plain linear ramp gives near-zero circular r2_cv).
 *
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "ManifoldProbeCircular".
 */
export interface ManifoldProbeCircular {
  /**
   * Period (in scalar units) whose circular coordinate is most decodable; null when the scalar range is too small to resolve one.
   */
  best_period: number | null;
  /**
   * Cross-validated R² of decoding the circular coordinate at `best_period` (averaged over cos and sin).
   */
  r2_cv: number | null;
  /**
   * In-sample R² of the circular decode at `best_period`.
   */
  r2_full: number | null;
}
/**
 * The per-position task scalar a supervised probe was fit against (present when `manifold --probe` was used). Lets the web app colour the manifold by the scalar instead of by generation step.
 *
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "ManifoldScalar".
 */
export interface ManifoldScalar {
  /**
   * Scalar name, e.g. `line_position` (characters since the last newline).
   */
  name: string;
  /**
   * Generation-step index for each value.
   */
  positions: number[];
  /**
   * Scalar value at each position, aligned with `positions`.
   */
  values: number[];
}
/**
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "Step".
 */
export interface Step {
  /**
   * Zero-indexed position in the generation loop.
   */
  step: number;
  selected: SelectedToken;
  raw: Distribution;
  processed: Distribution;
  /**
   * Optional per-layer logit-lens projections for this step. Present when a LogitLens probe was attached during generation. Ordered by layer_idx ascending.
   */
  logit_lens?: LogitLensLayer[];
  /**
   * Tier 1 inline attention summary, one entry per captured decoder layer. Absent for traces produced without an AttentionProbe.
   */
  attention?: AttentionLayerEntry[];
  /**
   * URI pointer to a Tier 2 sidecar payload (full attention distribution and/or raw Q/K/V tensors) for this step, or null when no sidecar was written. Sidecar files follow `docs/web/attention-sidecar.schema.json`.
   */
  attention_sidecar_ref?: string | null;
  /**
   * URI pointer to a Tier 2 activation sidecar payload (full per-(layer, submodule) hidden-state tensors) for this step, written when generated with `--capture-full-activations`. Null or absent when no activation sidecar was written.
   */
  activation_sidecar_ref?: string | null;
  /**
   * Selected token id at this step. Mirrors `selected.token_id`; carried here so the projected activation subset of this trace matches `activation.schema.json#/$defs/ActivationStep`.
   */
  token_id?: number;
  /**
   * Character offset of this step's decoded token in the concatenated decoded text. Drives cross-tokenizer alignment when two traces are compared by `compare_activations`.
   */
  decoded_text_offset?: number;
  /**
   * Per (layer, submodule) activation summary entries captured by an attached ActivationProbe. Ordering is layer-major then submodule-major following `activation_metadata.captured_submodules`. Absent for traces produced without an ActivationProbe.
   */
  activations?: ActivationLayerEntry[];
}
/**
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "SelectedToken".
 */
export interface SelectedToken {
  token_id: number;
  /**
   * Decoded text of the selected token (special tokens NOT skipped).
   */
  token: string;
}
/**
 * Outcome of one AdaptiveTokenProbe forward pass for one (step, source) pair.
 *
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "Distribution".
 */
export interface Distribution {
  /**
   * Number of candidates kept by the adaptive rule (clamped to [min_k, max_k]).
   */
  k_used: number;
  /**
   * Shannon entropy of the full next-token distribution, in nats.
   */
  entropy: number;
  /**
   * Cumulative probability mass covered by the kept candidates.
   */
  top_mass_used: number;
  selected_prob: number;
  /**
   * log(selected_prob + eps); may be -inf-ish but always finite under the probe's eps clamp.
   */
  selected_logprob: number;
  /**
   * 1-indexed rank of the selected token across the FULL vocabulary.
   */
  selected_rank: number;
  /**
   * Kept candidates, length == k_used, sorted by descending prob.
   */
  candidates: Candidate[];
}
/**
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "Candidate".
 */
export interface Candidate {
  /**
   * 1-indexed position within the kept candidates.
   */
  rank: number;
  token_id: number;
  token: string;
  prob: number;
  logprob: number;
}
/**
 * Logit-lens projection of one decoder layer's residual stream for one generation step.
 *
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "LogitLensLayer".
 */
export interface LogitLensLayer {
  /**
   * Zero-indexed decoder layer position.
   */
  layer_idx: number;
  /**
   * Highest-probability candidates after projecting this layer's hidden state through (optionally) the final LayerNorm and the lm_head.
   */
  top_k: LogitLensCandidate[];
  /**
   * Shannon entropy (nats) of this layer's full next-token distribution.
   */
  entropy: number;
  /**
   * 1-indexed rank of the step's selected token within this layer's distribution.
   */
  selected_token_rank: number;
  /**
   * Probability assigned to the step's selected token by this layer's distribution.
   */
  selected_token_prob: number;
}
/**
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "LogitLensCandidate".
 */
export interface LogitLensCandidate {
  /**
   * 1-indexed rank within the top_k candidates.
   */
  rank: number;
  token_id: number;
  token: string;
  prob: number;
  logprob: number;
}
/**
 * Tier 1 attention summary for a single (step, layer). The per-layer scalars here are the mean across heads.
 *
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "AttentionLayerEntry".
 */
export interface AttentionLayerEntry {
  /**
   * Zero-indexed decoder layer index; must appear in attention_metadata.captured_layers.
   */
  layer: number;
  /**
   * Mean Shannon entropy (nats) of the per-head attention distribution over previous positions, averaged across heads.
   */
  entropy: number;
  /**
   * Mean attention weight on the current (last) position, averaged across heads.
   */
  self_weight: number;
  /**
   * Mean attention weight on position 0 (typically the BOS / sink token), averaged across heads.
   */
  bos_weight: number;
  /**
   * Most-attended source positions for this layer, aggregated across heads, sorted by descending weight.
   */
  top_positions: AttentionTopPosition[];
  /**
   * Mean L2 norm of the current-token Q vector across heads.
   */
  q_norm: number;
  /**
   * Mean L2 norm of the current-token K vector across heads.
   */
  k_norm: number;
  /**
   * Mean L2 norm of the current-token V vector across heads.
   */
  v_norm: number;
  /**
   * Mean angle in degrees between the head's Q vector and the K vector of its top-attended source position, averaged across heads.
   */
  qk_alignment_angle: number;
  /**
   * Optional per-head Tier 1 scalars, one entry per attention head (length = attention_metadata.num_attention_heads), ordered by head index. Lets the Layer x Head grid color each head distinctly; absent on older traces, where the grid broadcasts the layer mean across all heads.
   */
  per_head?: {
    /**
     * This head's attention entropy in nats.
     */
    entropy: number;
    /**
     * This head's attention weight on the current (self) position.
     */
    self_weight: number;
    /**
     * This head's attention weight on the BOS position.
     */
    bos_weight: number;
    /**
     * This head's single largest source-position attention weight.
     */
    top1_weight: number;
    /**
     * L2 norm of this head's current-token Q vector.
     */
    q_norm: number;
    /**
     * L2 norm of this head's current-token K vector.
     */
    k_norm: number;
    /**
     * L2 norm of this head's current-token V vector.
     */
    v_norm: number;
  }[];
}
/**
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "AttentionTopPosition".
 */
export interface AttentionTopPosition {
  /**
   * Zero-indexed source position in the key sequence.
   */
  position: number;
  /**
   * Aggregate attention weight on this position (mean across heads).
   */
  weight: number;
}
/**
 * Summary statistics for one (step, layer, submodule) activation tensor. Mirrors `activation.schema.json#/$defs/ActivationLayerEntry`.
 *
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "ActivationLayerEntry".
 */
export interface ActivationLayerEntry {
  layer: number;
  submodule: string;
  l2_norm: number;
  mean_abs: number;
  sparsity: number;
  top_neurons: ActivationTopNeuron[];
}
/**
 * This interface was referenced by `Trace`'s JSON-Schema
 * via the `definition` "ActivationTopNeuron".
 */
export interface ActivationTopNeuron {
  index: number;
  value: number;
}
