#!/usr/bin/env node
// Regenerates the typed API client from the backend's OpenAPI spec.
//
// Source: web/frontend/openapi.json (checked-in snapshot of the FastAPI
// /openapi.json document, exported via `python -c "from
// llm_token_heatmap_api.main import create_app; ...; json.dump(...)"`).
//
// Output: web/frontend/src/api/generated/ (committed, marked AUTOGENERATED).
//
// The output is deterministic so CI can guard against drift: running this
// script twice on a clean tree must produce a zero diff.
//
// To refresh the snapshot against a live backend:
//   curl http://localhost:8000/openapi.json | python -m json.tool --sort-keys > web/frontend/openapi.json
// or (without a running backend, requires the backend package installed):
//   python -c "import json; from llm_token_heatmap_api.main import create_app; json.dump(create_app().openapi(), open('web/frontend/openapi.json','w'), indent=2, sort_keys=True)"

import { spawnSync } from 'node:child_process';
import { existsSync, rmSync, readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const frontendRoot = resolve(__dirname, '..');

const specPath = resolve(frontendRoot, 'openapi.json');
const outputDir = resolve(frontendRoot, 'src/api/generated');

if (!existsSync(specPath)) {
  console.error(
    `OpenAPI snapshot not found at ${specPath}.\n` +
      'Regenerate it from the backend:\n' +
      '  python -c "import json; from llm_token_heatmap_api.main import create_app; ' +
      "json.dump(create_app().openapi(), open('web/frontend/openapi.json','w'), indent=2, sort_keys=True)\"",
  );
  process.exit(1);
}

// Wipe the output dir first so removed operations don't linger as orphan files.
if (existsSync(outputDir)) {
  rmSync(outputDir, { recursive: true, force: true });
}

const bin = resolve(frontendRoot, 'node_modules/.bin/openapi');
const result = spawnSync(
  bin,
  [
    '--input',
    specPath,
    '--output',
    outputDir,
    '--client',
    'fetch',
    '--useUnionTypes',
    '--useOptions',
  ],
  { stdio: 'inherit' },
);

if (result.status !== 0) {
  console.error('openapi-typescript-codegen exited with non-zero status.');
  process.exit(result.status ?? 1);
}

// Post-process: the generator emits a `Date.now()` timestamp banner only when
// the spec advertises a version that contains a placeholder. With our
// FastAPI spec the banner is stable, but we still strip any trailing
// whitespace and normalize line endings so the directory is byte-identical
// across operating systems and re-runs.
function normalizeFile(path) {
  const text = readFileSync(path, 'utf8');
  const normalized = text.replace(/\r\n/g, '\n').replace(/[ \t]+$/gm, '');
  const ended = normalized.endsWith('\n') ? normalized : normalized + '\n';
  writeFileSync(path, ended, 'utf8');
}

function walk(dir) {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) {
      walk(p);
    } else if (p.endsWith('.ts')) {
      normalizeFile(p);
    }
  }
}

walk(outputDir);

console.log(`wrote ${outputDir}`);
