#!/usr/bin/env node
// Regenerates the canonical TypeScript types and runtime schema copies from
// the source-of-truth JSON Schemas under docs/web/.
//
// Outputs (all must remain in sync; all are autogenerated):
//   src/types/trace.ts                          — TypeScript types for trace.schema.json
//   src/lib/trace/trace.schema.json             — runtime copy used by Ajv
//   src/types/activation.ts                     — TS types for the activation + activation-diff schemas
//   src/lib/activation/activation.schema.json   — runtime copy of activation.schema.json
//   src/lib/activation/activation-diff.schema.json — runtime copy of activation-diff.schema.json
//
// The script is idempotent: running it twice on a clean tree produces a
// zero diff. CI relies on that to guard against drift.

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const frontendRoot = resolve(__dirname, '..');
const repoRoot = resolve(frontendRoot, '..', '..');

const BANNER = `/* eslint-disable */
// AUTOGENERATED — do not edit by hand.
// Source: docs/web/*.schema.json
// Regenerate with: npm run codegen
`;

// json-schema-to-typescript emits duplicate interfaces when a property that
// uses `$ref` also carries its own `description`. Strip those local
// descriptions before compiling so each $def maps to exactly one interface.
function stripRefSiblingDescriptions(node) {
  if (Array.isArray(node)) {
    node.forEach(stripRefSiblingDescriptions);
    return;
  }
  if (node && typeof node === 'object') {
    if (typeof node.$ref === 'string' && 'description' in node) {
      delete node.description;
    }
    for (const value of Object.values(node)) {
      stripRefSiblingDescriptions(value);
    }
  }
}

async function loadSchema(path) {
  const raw = await readFile(path, 'utf8');
  return JSON.parse(raw);
}

async function writeRuntimeSchemaCopy(schema, outputPath) {
  await mkdir(dirname(outputPath), { recursive: true });
  // Re-serialize with stable 2-space indent so the copy is idempotent.
  const stableSchema = JSON.stringify(schema, null, 2) + '\n';
  await writeFile(outputPath, stableSchema, 'utf8');
  console.log(`wrote ${outputPath}`);
}

async function compileSingle(schema, rootTitle, { withBanner = true } = {}) {
  const compileSchema = JSON.parse(JSON.stringify(schema));
  compileSchema.title = rootTitle;
  stripRefSiblingDescriptions(compileSchema);
  return compile(compileSchema, rootTitle, {
    bannerComment: withBanner ? BANNER : '',
    additionalProperties: false,
    declareExternallyReferenced: true,
    enableConstEnums: false,
    strictIndexSignatures: true,
    unreachableDefinitions: true,
    style: {
      singleQuote: true,
      trailingComma: 'all',
      semi: true,
      printWidth: 80,
    },
  });
}

async function generateTrace() {
  const schemaPath = resolve(repoRoot, 'docs/web/trace.schema.json');
  const typesPath = resolve(frontendRoot, 'src/types/trace.ts');
  const copyPath = resolve(frontendRoot, 'src/lib/trace/trace.schema.json');

  const schema = await loadSchema(schemaPath);
  const ts = await compileSingle(schema, 'Trace');
  await writeFile(typesPath, ts, 'utf8');
  console.log(`wrote ${typesPath}`);
  await writeRuntimeSchemaCopy(schema, copyPath);
}

async function generateActivation() {
  const activationSchemaPath = resolve(
    repoRoot,
    'docs/web/activation.schema.json',
  );
  const diffSchemaPath = resolve(
    repoRoot,
    'docs/web/activation-diff.schema.json',
  );
  const typesPath = resolve(frontendRoot, 'src/types/activation.ts');
  const activationCopyPath = resolve(
    frontendRoot,
    'src/lib/activation/activation.schema.json',
  );
  const diffCopyPath = resolve(
    frontendRoot,
    'src/lib/activation/activation-diff.schema.json',
  );

  const activationSchema = await loadSchema(activationSchemaPath);
  const diffSchema = await loadSchema(diffSchemaPath);

  // Compile each schema independently (their $defs reference siblings
  // by local pointer, so they can't share a synthetic root) and concatenate.
  const activationTs = await compileSingle(activationSchema, 'ActivationTrace');
  const diffTs = await compileSingle(diffSchema, 'ActivationDiff', {
    withBanner: false,
  });
  const extension = `import type { Step, Trace } from './trace';

/**
 * A Step from the canonical trace schema extended with the optional
 * activation fields a producer adds when an ActivationProbe is attached.
 * \`activations\` and \`decoded_text_offset\` are absent on traces produced
 * without an ActivationProbe; consumers MUST treat them as optional.
 */
export interface StepWithActivations extends Step {
  decoded_text_offset?: number;
  activations?: ActivationLayerEntry[];
}

/**
 * A canonical Trace extended with the optional activation fields. Producers
 * that emit activations inline (rather than as a separate
 * activation_trace.json file) MUST conform to this extended shape.
 */
export interface TraceWithActivations extends Omit<Trace, 'steps'> {
  activation_metadata?: ActivationMetadata;
  steps: StepWithActivations[];
}
`;
  const ts = activationTs + diffTs + extension;
  await writeFile(typesPath, ts, 'utf8');
  console.log(`wrote ${typesPath}`);

  await writeRuntimeSchemaCopy(activationSchema, activationCopyPath);
  await writeRuntimeSchemaCopy(diffSchema, diffCopyPath);
}

async function main() {
  await generateTrace();
  await generateActivation();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
